import type { Metadata } from "next";
import Provider from "./provider";
import "./globals.css";
import { Web3Provider } from "@/Context/ContractContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Provider>
        <Web3Provider>
        {children}
        </Web3Provider>
        </Provider>

      </body>
    </html>
  );
}
